spring.application.name=MoneyLog

spring.config.import=classpath:application-DB.properties,classpath:application-secret.properties
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true